### ISSUE TITLE
[FEATURE REQUEST]Add support for the purpur side of 1.20.1.

### ISSUE THREAD

**Issue by AOKAOKA** [oddlama/vane#262] opened 2024-07-14 20:05 UTC
It's a pity that I didn't run successfully on the server with purpur core. Does it not support purpur?

**Comment by oddlama** [comment] 2024-07-15 11:30
Officially we target PaperMC but AFAIK Purpur builds upon PaperMC so in theory it should be compatible. If you want us to have a look at it, please upload your logs.

**Comment by TarkinMX** [comment] 2024-08-11 02:21
I run my server on purpur and have no issues with vane. I'd like to see what the issue is that OP is having as well.

**Comment by oddlama** [comment] 2024-09-05 18:19
Closing this as I cannot reproduce the error. Feel free to repost if you have logs.

**Closed by oddlama** 2024-09-05 18:19 UTC
