### ISSUE TITLE
1.20.4: Cannot use Backpack or Pouch.

### ISSUE THREAD

**Issue by jacklollz2** [oddlama/vane#229] opened 2024-01-02 02:57 UTC
git-Purpur-2112 (MC: 1.20.4)
Vane v1.14.0
ProtocolLib #679 80aa42009981b505370b00dd71af6d4e41726f38

```
[02:44:08] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to vane-trifles v1.14.0
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 33 path $.translate
        at com.google.gson.Gson.fromJson(Gson.java:1241) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:?]
        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:89) ~[adventure-text-serializer-gson-4.15.0.jar:?]
        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:41) ~[adventure-text-serializer-gson-4.15.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftMetaItem.displayName(CraftMetaItem.java:876) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftMetaBlockState.displayName(CraftMetaBlockState.java:20) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at org.oddlama.vane.trifles.StorageGroup.open_block_state_inventory(StorageGroup.java:197) ~[vane-trifles-1.14.0.jar:?]
        at org.oddlama.vane.trifles.items.storage.Backpack.on_player_right_click(Backpack.java:62) ~[vane-trifles-1.14.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor97.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2112]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:592) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:539) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2068) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1485) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1462) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1385) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1363) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 33 path $.translate
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659) ~[gson-2.10.1.jar:?]
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1044) ~[gson-2.10.1.jar:?]
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826) ~[gson-2.10.1.jar:?]
        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:145) ~[adventure-text-serializer-gson-4.15.0.jar:?]
        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:77) ~[adventure-text-serializer-gson-4.15.0.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:204) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        ... 37 more
```

**Comment by oddlama** [comment] 2024-01-02 12:15
Unfortunately I can't reproduce this on PaperMC-365, so either there's an issue in your Purpur version, or your world is in a corrupted state. If it is the former, waiting for an update of Purpur might fix it.

**Comment by jacklollz2** [comment] 2024-01-02 17:17
> Unfortunately I can't reproduce this on PaperMC-365, so either there's an issue in your Purpur version, or your world is in a corrupted state. If it is the former, waiting for an update of Purpur might fix it.

This is a fresh server. Maybe it's Purpur, but I assure you everything is fresh and recently created.
It reminds me of a previous issue I had related to these items. https://github.com/oddlama/vane/issues/175
I urge you to address this.

**Comment by oddlama** [comment] 2024-01-02 17:54
Oh I'm not dismissing the issue, but I cannot fix something unless I can reproduce it and figure out what's going wrong..
I also just tested it using the latest Purpur build with vane v1.14.0 and it just works as expected.

> [18:51:55 INFO]: This server is running Purpur version git-Purpur-2113 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 8373071 on HEAD)

**Comment by oddlama** [comment] 2024-01-02 17:57
The fact that your server complains about `Unterminated string at line 1 column 33 path $.translate` is hinting at an error in item deserialization, and those usually occur when you have a corrupt world. Vane itself doesn't mess with stuff like that at all, so either your server crashed and corrupted the item, or another plugin is responsible.

**Comment by jacklollz2** [comment] 2024-01-02 18:02
> The fact that your server complains about `Unterminated string at line 1 column 33 path $.translate` is hinting at an error in item deserialization, and those usually occur when you have a corrupt world. Vane itself doesn't mess with stuff like that at all, so either your server crashed and corrupted the item, or another plugin is responsible.

It happens on different worlds and with newly created items with /customitem.

**Comment by oddlama** [comment] 2024-01-02 18:07
And you have no other plugins?

**Comment by jacklollz2** [comment] 2024-01-02 18:07
> And you have no other plugins?

No other plugins with this error, and no gameplay or server issues, such as problems generating items, renaming them in anvils, etc.

Plugins: CoreProtect-22.2, FastAsyncWorldEdit-Bukkit-2.8.5-SNAPSHOT-639, Minepacks-v2.4.24, PlaceholderAPI-2.11.5, TreeFeller-1.22.2, Vault, SkBee-3.0.1, EssentialsX-2.20.1, InventoryRollbackPlus-1.6.14, MyWorlds-1.20.4-v3-SNAPSHOT-264, Plan-5.6-build-2614, vane-core-1.14.0, worldguard-bukkit-7.0.10-SNAPSHOT-dist, BKCommonLib-1.20.4-v1-1663, EssentialsXChat-2.20.1, Skript (no skripts), EssentialsX.Selectors.2.0, InvUnload-5.0.2, OpenInv-4.4.2, ProtocolLib, skript-reflect, vane-enchantments-1.14.0, skript-reflect-2.4-dev1, Chunky-1.3.92, FastAsyncVoxelSniper-3.0.0, LuckPerms-Bukkit-5.4.113, OtherDrops3.2.8-b285, vane-trifles-1.14.0, RoseStacker-1.5.16

**Comment by oddlama** [comment] 2024-01-02 18:16
Did you test it with just vane enabled to rule out that another plugin causes it?

**Comment by jacklollz2** [comment] 2024-01-02 18:30
> Did you test it with just vane enabled to rule out that another plugin causes it?

I had these plugins before. I can go through every plugin, enabling and disabling them one by one, just like the last time, but honestly why should I? The last time it was only your plugin, and again, it's only your plugin.

**Comment by oddlama** [comment] 2024-01-02 18:37
> I can go through every plugin, enabling and disabling them one by one

Or you can just disable everything except for vane and check if it works then. That way you can immediately rule out whether it is another plugin's fault.

> but honestly why should I?

You are the only one who has the issue so far, so you are the only one who can test it. If you come here and demand free support, I would at least appreciate it if you would put in some effort, too.

> The last time it was only your plugin, and again, it's only your plugin. I fixed this issue the last time with your plugin by completely rebuilding the server from the ground up.

If you feel like vane is the root cause for all your troubles, I would advise you to uninstall it.

**Comment by jacklollz2** [comment] 2024-01-02 18:40
> > I can go through every plugin, enabling and disabling them one by one
> 
> Or you can just disable everything except for vane and check if it works then. That way you can immediately rule out whether it is another plugin's fault.
> 
> > but honestly why should I?
> 
> You are the only one who has the issue so far, so you are the only one who can test it. If you come here and demand free support, I would at least appreciate it if you would put in some effort, too.
> 
> > The last time it was only your plugin, and again, it's only your plugin. I fixed this issue the last time with your plugin by completely rebuilding the server from the ground up.
> 
> If you feel like vane is the root cause for all your troubles, I would advise you to uninstall it.

This is on a different machine entirely, with a different install, etc.

People have been complaining about duplicating items with your portal plugin.

If you don't want to repair this recurring issue, then absolutely, I will discontinue future use of vane.

**Comment by oddlama** [comment] 2024-01-02 18:58
> This is on a different machine entirely, with a different install, etc.

I cannot debug based on anecdotal evidence. If you want to get to the bottom of this, then this will require some testing on your side unless you can tell me how to reproduce it.

> If you don't want to repair this recurring issue [...]

Did you read anything of what I wrote? I'm very sorry you are having issues, but with this attitude you are not helping in any way. Please have some decency and don't just come here and demand something when - in fact - everything here is provided to you for free at no charge. It is simply unlikely that this will get fixed if you are the only one with the issue and are not willing to help to get the necessary information for debugging. What are you expecting?

I'm going to close this now as this is neither constructive nor helpful. If you change your mind later and want to do this properly, I'm always happy to help if you are too. Please open a new issue in that case.

**Closed by oddlama** 2024-01-02 18:58 UTC
