### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by ABKQPO** [oddlama/vane#211] opened 2023-08-07 09:30 UTC
When I use protocolib's build #665, the vane-core plugin fails to load without any error, the server side is purpur1.20.1-2011, and the plugin version is 1.12.3

**Comment by oddlama** [comment] 2023-08-07 18:17
I verified that it loads fine for with newest ProtocolLib-665 and Paper-108, so either this is an upstream issue with Purpur or something else is wrong on your setup.

**Comment by oddlama** [comment] 2023-09-29 18:48
Closing since this could not be reproduced

**Closed by oddlama** 2023-09-29 18:48 UTC
