### ISSUE TITLE
Your resource pack download seems to have failed.

### ISSUE THREAD

**Issue by ryantheleach** [oddlama/vane#80] opened 2021-12-21 03:43 UTC
![image](https://user-images.githubusercontent.com/141554/146867282-38b48a7a-737a-4f37-b67a-937d804b4366.png)

Whenever trying to log into my server with vane, all I get is this.

vane-core
vane-portals
vane-trifles
version 1.6.6

**Comment by oddlama** [comment] 2021-12-21 12:54
Can you check your client's logfiles `%APPDATA%/.minecraft/logs/latest.log` or something? A detailed error message will be included there.

**Comment by ryantheleach** [comment] 2021-12-22 05:07
```
[15:34:14] [Render thread/INFO]: [CHAT] 05:04:13 ryan_the_leach is back after being idle for 1h 1m 1s
[15:34:16] [Render thread/INFO]: Reloading ResourceManager: Default, Programmer Art, derpcoin datapack
[15:34:17] [Server Pinger #2/ERROR]: Can't ping marcuto.serv.lol: Unknown host
[15:34:18] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Wave Link System (Elgato Wave:1)
[15:34:18] [Render thread/INFO]: Sound engine started
[15:34:18] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[15:34:18] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[15:34:18] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[15:34:18] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[15:34:18] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[15:34:18] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[15:34:18] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[15:34:18] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[15:34:18] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[15:34:18] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[15:34:21] [Render thread/INFO]: Connecting to 120.138.17.189, 25565
[15:34:22] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:34:22] [Render thread/WARN]: Unknown custom packed identifier: minecraft:register
[15:34:23] [Render thread/INFO]: [CHAT] The last player only logged off less than a minute ago.
[15:34:23] [Render thread/INFO]: [CHAT] ryan_the_leach joined the game
[15:34:23] [Render thread/INFO]: Loaded 359 advancements
[15:34:24] [Netty Client IO #9/INFO]: Found file C:\Users\ryant\AppData\Roaming\.minecraft\server-resource-packs\c0ce2d2efa640d0cb7a7b8943ef648e5aecdaa73 matching requested hash a08c1ad5e87248a0af5f959a4cd69fde4adc0161
[15:34:24] [Netty Client IO #9/INFO]: Applying server pack C:\Users\ryant\AppData\Roaming\.minecraft\server-resource-packs\c0ce2d2efa640d0cb7a7b8943ef648e5aecdaa73
[15:34:24] [Render thread/INFO]: Reloading ResourceManager: Default, Programmer Art, derpcoin datapack, c0ce2d2efa640d0cb7a7b8943ef648e5aecdaa73
[15:34:24] [Worker-Main-28/WARN]: Codepoint 'df' declared multiple times in minecraft:textures/font/nonlatin_european.png
[15:34:24] [Worker-Main-28/WARN]: Codepoint '406' declared multiple times in minecraft:textures/font/nonlatin_european.png
[15:34:26] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Wave Link System (Elgato Wave:1)
[15:34:26] [Render thread/INFO]: Sound engine started
[15:34:26] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[15:34:26] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[15:34:26] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[15:34:26] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[15:34:26] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[15:34:26] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[15:34:26] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[15:34:26] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[15:34:26] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[15:34:26] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[15:34:31] [Render thread/INFO]: [CHAT] Are you sure you wish to reload your server? Doing so may cause bugs and memory leaks. It is recommended to restart instead of using /reload. To confirm, please type /reload confirm
[15:34:33] [Render thread/INFO]: [CHAT] Please note that this command is not supported and may cause issues when using some plugins.
[15:34:33] [Render thread/INFO]: [CHAT] If you encounter any issues please use the /stop command to restart your server.
[15:34:35] [Render thread/INFO]: Loaded 359 advancements
[15:34:36] [Render thread/INFO]: Reloading ResourceManager: Default, Programmer Art, derpcoin datapack
[15:34:36] [Server Pinger #2/ERROR]: Can't ping marcuto.serv.lol: Unknown host
[15:34:37] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Wave Link System (Elgato Wave:1)
[15:34:37] [Render thread/INFO]: Sound engine started
[15:34:38] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[15:34:38] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[15:34:38] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[15:34:38] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[15:34:38] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[15:34:38] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[15:34:38] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[15:34:38] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[15:34:38] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[15:34:38] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[15:34:57] [Render thread/INFO]: Connecting to tavernfiremc.ruok.org, 25565
[15:35:00] [Render thread/INFO]: Connecting to 120.138.17.189, 25565
[15:35:01] [Netty Client IO #14/INFO]: Found file C:\Users\ryant\AppData\Roaming\.minecraft\server-resource-packs\eccbc4040c79541ce95814bdcbd8a841527b493d matching requested hash 1bbc0027ae970ce71fd5fed1f14294b8fd77e5d8
[15:35:01] [Netty Client IO #14/INFO]: Applying server pack C:\Users\ryant\AppData\Roaming\.minecraft\server-resource-packs\eccbc4040c79541ce95814bdcbd8a841527b493d
[15:35:01] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:35:01] [Render thread/WARN]: Unknown custom packed identifier: minecraft:register
[15:35:02] [Render thread/INFO]: Reloading ResourceManager: Default, Programmer Art, derpcoin datapack, eccbc4040c79541ce95814bdcbd8a841527b493d
[15:35:02] [Render thread/INFO]: Loaded 359 advancements
[15:35:02] [Netty Client IO #14/INFO]: Found file C:\Users\ryant\AppData\Roaming\.minecraft\server-resource-packs\c0ce2d2efa640d0cb7a7b8943ef648e5aecdaa73 matching requested hash a08c1ad5e87248a0af5f959a4cd69fde4adc0161
[15:35:02] [Netty Client IO #14/INFO]: Applying server pack C:\Users\ryant\AppData\Roaming\.minecraft\server-resource-packs\c0ce2d2efa640d0cb7a7b8943ef648e5aecdaa73
[15:35:04] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Wave Link System (Elgato Wave:1)
[15:35:04] [Render thread/INFO]: Sound engine started
[15:35:04] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[15:35:04] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[15:35:04] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[15:35:04] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[15:35:04] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[15:35:04] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[15:35:04] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[15:35:04] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[15:35:04] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[15:35:04] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[15:35:06] [Render thread/INFO]: Reloading ResourceManager: Default, Programmer Art, derpcoin datapack
[15:35:09] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Wave Link System (Elgato Wave:1)
[15:35:09] [Render thread/INFO]: Sound engine started
[15:35:09] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[15:35:09] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[15:35:09] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[15:35:09] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[15:35:09] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[15:35:09] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[15:35:09] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[15:35:10] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[15:35:10] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[15:35:10] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas

```

**Comment by oddlama** [comment] 2021-12-22 19:43
Your logs say it applied the texture pack just fine... Seems like a client issue. Maybe try deleting the `server-resource-packs` folder to force a re-download.

**Comment by ryantheleach** [comment] 2021-12-28 11:56
Same result.

**Comment by oddlama** [comment] 2021-12-28 14:22
Reloading is generally not a supported operation by spigot/papermc. I only provide it as a convenience to reload vane specific configuration, but certain things in the server still won't like it (as for example the resource pack distributor). If in doubt you should always restart.

I can assure you that vane is not involved in this problem at all. The resource pack distribution is an integral part of the standard minecraft server and vane is only configuring it for you. As you have the same configuration as everyone else, it must be a client side issue. Sure there is the workaround of disabling the distributor, but that is fighting the symptoms instead of the cause.

I've got some more questions that could help:
* Do you have any client side mods installed?
* Could you provide the full latest.log when the error happens? There should be an error.
* Can the computer on which the problem happens access the resource pack directly? (https://oddlama.github.io/vane/resourcepacks/v1.6.7.zip)

**Comment by ryantheleach** [comment] 2021-12-28 17:33
> Do you have any client side mods installed?

No.

Could you provide the full latest.log when the error happens? There should be an error.

I assure you, there's no error on the server or client, or any helpful information at all, I looked at both the server and client logs. without enabling extra debug configurations (which I don't know how to do offhand).

Can the computer on which the problem happens access the resource pack directly? (https://oddlama.github.io/vane/resourcepacks/v1.6.7.zip)

Yes I've downloaded it just now from your link, and going to have a play.

The only thing I can think of, is if vane is in conflict with another plugin or resource pack.

**Comment by oddlama** [comment] 2021-12-28 23:48
Considering you understand java, have a look at the following: https://github.com/oddlama/vane/blob/b0094d7181c60c946e79ac0ccd1dc78f8579b6a3/vane-core/src/main/java/org/oddlama/vane/core/ResourcePackDistributor.java#L109-L134

This is everything vane actually does (except for sanitizing config) regarding resource packs. Offical resource pack api,
just passes the url and the api together, minecraft handles the rest. Not sure how anything could go wrong there or how any other plugins could interfere except by specifically removing the set resource pack if that's even possible.

**Comment by oddlama** [comment] 2022-01-01 00:57
Resolution for future readers: Another resource pack had been manually set in server.properties, which interferes with vane, which is trying to use the same built-in mechanism. Will add a warning for that case in the future, tracked via #101.

**Closed by oddlama** 2022-01-01 00:57 UTC
Labels: support

**Comment by ryantheleach** [comment] 2022-01-01 07:21
It hadn't been set in server .properties for what it's worth, I mistook having a folder in datapacks (that included assets) as having a resource pack configured. unsure if that's the root cause.

**Comment by ryantheleach** [comment] 2022-01-01 07:24
Which caused me to do some more investigation, it's probably ca conflict with EmojiChat plugin. 
![image](https://user-images.githubusercontent.com/141554/147845942-4038ff33-3bb8-4f26-bde5-3875b4b2c201.png)

**Comment by pyran0** [comment] 2023-04-05 00:31
hey so it seems like vane will not let me attach any resource pack thru my serverproperty files is there a way i can disable it autogenerating the resource pack download it myself so then i can merge it with the one i need to and then put the merged one in server properties and if i did that wud vane still work?

**Comment by oddlama** [comment] 2023-04-05 10:09
Please don't hijack old topics. If you have a question, please ask on our discord.
