### ISSUE TITLE
Fast Walking: Inconsistent & Discrepant operation.

### ISSUE THREAD

**Issue by jacklollz2** [oddlama/vane#232] opened 2024-01-07 06:38 UTC
Part of your Fast Walking description says "Materials on which **players** will walk faster."
This does not apply to just players, it is all mobs. Including hostile.
Numerous of my players have been attacked by super-fast spiders, as the speed effect is not the same exponent for each mob. Players speed effect vs Spider speed effect vs etc speed effect is different.

Add an option to make Fast Walking work only on players.

**Comment by Serial-ATA** [comment] 2024-01-07 06:44
See #228

**Comment by oddlama** [comment] 2024-01-07 12:07
> Players speed effect vs Spider speed effect vs etc speed effect is different.

They all get the same Speed I buff as if you had thrown a speed I potion on them.

Closing as duplicate of #227.

**Closed by oddlama** 2024-01-07 12:07 UTC
