### ISSUE TITLE
Can't craft Ancient Tome of the Gods

### ISSUE THREAD

**Issue by NyhmsQuest** [oddlama/vane#81] opened 2021-12-22 18:37 UTC
![image](https://user-images.githubusercontent.com/3873370/147139712-95b16b3b-7f37-4af3-8b1f-d8eb20d084d9.png)

Recipe isn't working

**Comment by oddlama** [comment] 2021-12-22 19:38
what enchantments do you have on the two books?

**Comment by NyhmsQuest** [comment] 2021-12-22 19:39
I tried 2 random enchanted books and after that I tried 2 Efficiency 5 books

**Comment by oddlama** [comment] 2021-12-22 19:47
Is the recipe listed in your recipe book? And did you maybe e.g. rename the book of knowledge?

**Comment by NyhmsQuest** [comment] 2021-12-22 19:52
It's listed in the recipe book
![image](https://user-images.githubusercontent.com/3873370/147147747-45414bd0-8f9f-45e4-b8c9-c47d203968a2.png)

**Comment by oddlama** [comment] 2021-12-25 00:15
It's unfortunately very hard for me to reproduce this. Can you post the NBT content of the tome and the two books?

**Comment by NyhmsQuest** [comment] 2021-12-26 11:12
Apologize for the late reply, but how do I get the NBT content of them?

**Comment by oddlama** [comment] 2021-12-26 12:57
Take the item in your hand and execute `data get entity yourplayername SelectedItem`.
I recommend doing it from the console so you can copy the output

**Comment by NyhmsQuest** [comment] 2021-12-26 13:06
[14:05:04 INFO]: Argathen has the following entity data: {id: "minecraft:book", tag: {display: {Name: '{"italic":false,"text":"Ancient Tome of Knowledge"}', Lore: []}, CustomModelData: 7823790}, Count: 64b}

[14:05:37 INFO]: Argathen has the following entity data: {id: "minecraft:enchanted_book", tag: {display: {Lore: []}, StoredEnchantments: [{id: "minecraft:sharpness", lvl: 5s}]}, Count: 1b}

[14:05:42 INFO]: Argathen has the following entity data: {id: "minecraft:enchanted_book", tag: {display: {Lore: []}, StoredEnchantments: [{id: "minecraft:sharpness", lvl: 5s}]}, Count: 1b}

[14:05:46 INFO]: Argathen has the following entity data: {id: "minecraft:nautilus_shell", Count: 1b}

[14:05:49 INFO]: Argathen has the following entity data: {id: "minecraft:nether_star", Count: 1b}

That's all the items I used to try and craft it.

**Comment by oddlama** [comment] 2021-12-26 13:29
Thanks! With your items I can reproduce the problem and I also have a guess as to why it happens. I think you acquired the book while having client side translations disabled, or you once renamed the tome. Unfortunately I'm not sure if I can fix it. Let me explain:

Recipes can either ignore all NBT data or require a full match. For custom items, I must match nbt data, as the `CustomModelData` tag tells me which item it is. But that has the unfortunate side-effect that every other NBT data must
also match exactly, and minecraft upstream never gave us a workaround for this issue. This means that the recipe requires the tome to be in exactly the same state as it was when it was created. Renaming it would mean the NBT changes and it doesn't match anymore.

If you acquire the book while client side translations are disabled, and then enable it again, the book will have a different tag than what the server thinks it should have, and there's nothing I can really do about it. Also if I would add another recipe for other configurations, there would then be several craftable tomes in the recipe book which would be highly confusing.

**Comment by NyhmsQuest** [comment] 2021-12-26 13:32
I never touched translations and I never renamed the book. It was aquired by copying it in creative mode.

**Comment by oddlama** [comment] 2021-12-26 13:40
Ohh that also makes total sense. Creative mode duplication doesn't actually duplicate an item on the server. Instead the client lets the server create a new stack with whatever data it sends. So probably the client resolves the translation when duplicating causing the bug. That's a real bummer. That's an unfixable client side issue. :/

But I can recommend a workaround to duplicate tomes: Use minecraft's `give` command with the correct nbt tag.
Basically give yourself a real tome using `/customitem give vane_enchantments:book_ancient_tome_of_knowledge`,
then use `data get entity yourplayername SelectedItem` to get the full nbt tag of the correct item, and lastly use minecraft's internal `give` command to create as many as you need. The required tag is inside the `tag:` attribute.

So basically as of vane `1.16.7` the correct command would be:
`give @p miencraft:book{display: {Name: '{"italic":false,"translate":"vane_enchantments.item_ancient_tome_of_knowledge.book.name"}'}, CustomModelData: 7823790}`

**Comment by NyhmsQuest** [comment] 2021-12-26 13:45
I feel like I remember back in 1.17 in an earlier build testing the books by finding 1 and then using creative mode middle mouse button to copy a stack of it and crafting enchants.

**Comment by oddlama** [comment] 2021-12-26 13:48
I think the client started resolving the translations on copy in 1.18, but I'm not 100% sure. But I can assure you that nothing in the plugin has changed regarding this functionality since 1.16. It definitely is a client side issue, and maybe a newly introduced one.

**Comment by oddlama** [comment] 2022-02-04 00:41
Closing as I couldn't reproduce this in minecraft 1.18. If the issue re-appears, please let me know!

**Closed by oddlama** 2022-02-04 00:41 UTC
